services:
  hashcraft:
    image: hashcraft
    container_name: hashcraft
    restart: always
    ports:
      - 5:5
  ngrok-hashcraft:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    container_name: ngrok-hashcraft
    command:
      - "http"
      - "--url=blessed-dodo-rich.ngrok-free.app"
      - "https://localhost:5"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 9:4040